Ether card msp430 port
bluebandit21/magic-wifi pull request #6
Opened 2022-10-24 22:51 UTC by bluebandit21

With this code, the EtherCard port to the MSP430 is able to successfully send the raw Ethernet frame containing the message "Hello"!

More work is definitely required -- the code desperately needs to be cleaned up a bit, and various things are hard-coded that really shouldn't be, but it's a really solid start.

2022-10-24 22:52 UTC, bluebandit21 commented
@Santa-Bunny Note: This does require the driverlib copy taken from [7e0d35a](https://github.com/bluebandit21/magic-wifi/commit/7e0d35a2a5def2336ba607aa769682530a011e84) to work; I didn't want to rebase this entire branch to include it in case anyone happened to be working off of this.

You should merge develop into this locally before testing if that's something you want to do pre-merge :)

2022-10-25 15:01 UTC, Santa-Bunny requested changes
I am not sure why in the dev/EtherCard_MSP430FR2355 library you have added Arduino examples in the examples folder that can also be seen in dev/EtherCard_minimized. I would recomment removing the entire examples folder alltogether from this section.

As well, dev/EtherCard_MSP430FR2355/CONTRIBUTING.md and README.md reference Arduino instead of the MSP430. If this is what you would like I would recommend changing the folder name to not reflect the MSP430FR2355, otherwise I would like to see the folder more reflective of MSP430FR2355 code.

2022-10-28 00:05 UTC, bluebandit21 commented
> @Santa-Bunny Note: This does require the driverlib copy taken from [7e0d35a](https://github.com/bluebandit21/magic-wifi/commit/7e0d35a2a5def2336ba607aa769682530a011e84) to work; I didn't want to rebase this entire branch to include it in case anyone happened to be working off of this.
> 
> You should merge develop into this locally before testing if that's something you want to do pre-merge :)

EDIT: I did just rebase the entire branch at the end of the day anyway, so this no longer applies.

2022-10-28 14:32 UTC, Santa-Bunny approved these changes

2022-10-28 14:32 UTC, merged